### ISSUE TITLE
Help with UnboundLocalError when running SQANTI

### ISSUE THREAD

**Issue by fh-zju** [ConesaLab/SQANTI#2]
Hello,

I got an UnboundLocalError when running sqanti_qc.py with python2.7. It was reported as below. Could you please help? Thanks!

Best,
Feng

**** Performing Classification of Isoforms...
Traceback (most recent call last):
  File "/path/sqanti_qc.py", line 1980, in <module>
    main()
  File "/path/sqanti_qc.py", line 1976, in main
    run(args)	
  File "/path/sqanti_qc.py", line 1717, in run
    isoforms_inf = isoformClassification(args, myQueryTranscripts_list, transcripts_chrom_1exon, transcripts_chrom_exons, transcripts_gene, transcripts_gene_chrom, seq, indelsJunc)
  File "/path/sqanti_qc.py", line 1590, in isoformClassification
    (assoc, junctions, index_chrom_exons, index_chrom_1exon) = transcriptsKnownSpliceSites(transcripts_chrom_1exon, transcripts_chrom_exons, line_split, index_chrom_exons, index_chrom_1exon, transcripts_gene, seq, args.window)
  File "/path/sqanti_qc.py", line 880, in transcriptsKnownSpliceSites
    percA = float(downTTS.count('A'))/nPolyA*100
UnboundLocalError: local variable 'downTTS' referenced before assignment

**Comment by aarzalluz** [comment]
Hi @fh-zju,

I just wanted to notify you that, unfortunately, SQANTI is deprecated and will no longer be updated or maintained. Please consider switching to [SQANTI3](https://github.com/ConesaLab/SQANTI3), which has a broader catalogue of QC descriptors and is updated to run on **python3**.

Best,


Ángeles

**Comment by fh-zju** [comment]
Hi Ángeles,Thanks for your reply and your nice work on developing and maintaining the app. It is very helpful.Feng
